### ISSUE TITLE
Support hot reloading with CLI

### ISSUE THREAD

**Issue by wwwillchen** [google/optic#7]
**Goal:** Provide hot reloading for developers using Optic.

**Desired behavior:** When an Optic application is modified under development mode, we will send a signal from the server to client to save the client state to a persistent web storage (e.g localStorage) and trigger a reload.

# Design notes

ibazel (https://github.com/bazelbuild/bazel-watcher) provides a helpful wrapper around bazel which watches for filesystem changes and triggers a livereload.

## Prior Art

- [ts_devserver](https://github.com/angular/angular-bazel-example/wiki/Running-a-devserver-under-Bazel)
  - [code](https://github.com/bazelbuild/rules_nodejs/blob/b836b11a32bb6ade50c769e06b7d93e606d342d3/third_party/github.com/bazelbuild/rules_typescript/devserver/main.go#L61)

## TODO:

- [ ] Within `cli.py`, detect whether `IBAZEL_LIVERELOAD_URL` environmental variable is present and use it to inject a script in index.html.
- [ ] scan stdin for commands [golang example](https://github.com/bazelbuild/bazel-watcher/blob/97249d3b6d6470894426dcca6d8a61725f6a7e97/example_client/example_client.go#L54). 

Potential implementation:
```py
def monitor_stdin():
    while True:
        line = sys.stdin.readline().strip()
        if line == "SOURCE_CHANGE":
            reexecute()

stdin_thread = threading.Thread(target=monitor_stdin)
stdin_thread.daemon = True
stdin_thread.start()
```

- [ ] Add the following tags to Bazel target: 
```
 tags = [
        # This tag starts the live_reload server inside iBazel and instructs it to send reload events to webbrowsers.
        "ibazel_live_reload",
        # This tag instructs ibazel to pipe into stdin a event describing actions.
        "ibazel_notify_changes",
    ],
```
